### ISSUE TITLE
Could you please create a short VDO showing how to deploy Cloud function + Pubsub + GCS

### ISSUE THREAD

**Issue by noppGithub** [fingineering/GCPFunctionDevOpsDemo#1]
For example, A cloud function that get the data from pubsub and store them as text file in GCS

**Comment by fingineering** [comment]
If you mean a video, probably not. But an example might be possible

**Comment by noppGithub** [comment]
@fingineering an example is great, I'm looking for a sample to deploy my Flask(Python) application on a Cloud Function with Pub/Sub trigger when a new file is uploaded to GCS.

Please let me know if I can buy you a cup of coffee :)

**Comment by fingineering** [comment]
If you already have a running Flask application, you can easily deploy it on Google App Engine. Add a app.yaml file to your project folder:

```yaml
runtime: python39

instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 0

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static
  secure: always

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
  secure: always

service_account: your-google_service-account

includes:
  - environment_vars.yaml

entrypoint: gunicorn -b :8080 -w 1 main:app
```

https://www.buymeacoffee.com/owil

Then use gcloud to [deploy](https://cloud.google.com/sdk/gcloud/reference/app/deploy} the app on App Engine

```bash
gcloud app deploy
```
